/* tslint:disable */
/* eslint-disable */
/**
 * Mentori API
 * A mentor-mentee matching platform API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mentori.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ModelsAuthResponse
 */
export interface ModelsAuthResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsAuthResponse
     */
    'token'?: string;
    /**
     * 
     * @type {ModelsUserResponse}
     * @memberof ModelsAuthResponse
     */
    'user'?: ModelsUserResponse;
}
/**
 * 
 * @export
 * @interface ModelsCreateProfileRequest
 */
export interface ModelsCreateProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateProfileRequest
     */
    'avatar_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateProfileRequest
     */
    'bio'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsCreateProfileRequest
     */
    'expertise'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateProfileRequest
     */
    'first_name': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsCreateProfileRequest
     */
    'interests'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateProfileRequest
     */
    'last_name': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateProfileRequest
     */
    'linkedin_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateProfileRequest
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateProfileRequest
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateProfileRequest
     */
    'website_url'?: string;
}
/**
 * 
 * @export
 * @interface ModelsErrorResponse
 */
export interface ModelsErrorResponse {
    /**
     * 
     * @type {number}
     * @memberof ModelsErrorResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsErrorResponse
     */
    'error'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsErrorResponse
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ModelsLoginRequest
 */
export interface ModelsLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ModelsProfile
 */
export interface ModelsProfile {
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'avatar_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'bio'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'created_at'?: string;
    /**
     * Array of skills/expertise
     * @type {Array<string>}
     * @memberof ModelsProfile
     */
    'expertise'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'id'?: string;
    /**
     * Array of interests
     * @type {Array<string>}
     * @memberof ModelsProfile
     */
    'interests'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsProfile
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'linkedin_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'user_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsProfile
     */
    'website_url'?: string;
}
/**
 * 
 * @export
 * @interface ModelsRegisterRequest
 */
export interface ModelsRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsRegisterRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsRegisterRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsRegisterRequest
     */
    'role': ModelsRegisterRequestRoleEnum;
}

export const ModelsRegisterRequestRoleEnum = {
    Mentor: 'mentor',
    Mentee: 'mentee',
    Admin: 'admin'
} as const;

export type ModelsRegisterRequestRoleEnum = typeof ModelsRegisterRequestRoleEnum[keyof typeof ModelsRegisterRequestRoleEnum];

/**
 * 
 * @export
 * @interface ModelsUpdateProfileRequest
 */
export interface ModelsUpdateProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateProfileRequest
     */
    'avatar_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateProfileRequest
     */
    'bio'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsUpdateProfileRequest
     */
    'expertise'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateProfileRequest
     */
    'first_name'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsUpdateProfileRequest
     */
    'interests'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsUpdateProfileRequest
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateProfileRequest
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateProfileRequest
     */
    'linkedin_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateProfileRequest
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateProfileRequest
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUpdateProfileRequest
     */
    'website_url'?: string;
}
/**
 * 
 * @export
 * @interface ModelsUserResponse
 */
export interface ModelsUserResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsUserResponse
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserResponse
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserResponse
     */
    'id'?: string;
    /**
     * 
     * @type {ModelsProfile}
     * @memberof ModelsUserResponse
     */
    'profile'?: ModelsProfile;
    /**
     * 
     * @type {string}
     * @memberof ModelsUserResponse
     */
    'role'?: string;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Authenticate user with email and password
         * @summary User login
         * @param {ModelsLoginRequest} request User login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost: async (request: ModelsLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('authLoginPost', 'request', request)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invalidate user session (client-side token removal)
         * @summary User logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get current authenticated user\'s profile
         * @summary Get user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProfileGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new user account with email, password, and role
         * @summary Register a new user
         * @param {ModelsRegisterRequest} request User registration data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost: async (request: ModelsRegisterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('authRegisterPost', 'request', request)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Authenticate user with email and password
         * @summary User login
         * @param {ModelsLoginRequest} request User login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginPost(request: ModelsLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsAuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Invalidate user session (client-side token removal)
         * @summary User logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLogoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get current authenticated user\'s profile
         * @summary Get user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authProfileGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authProfileGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authProfileGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new user account with email, password, and role
         * @summary Register a new user
         * @param {ModelsRegisterRequest} request User registration data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRegisterPost(request: ModelsRegisterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsAuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRegisterPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Authenticate user with email and password
         * @summary User login
         * @param {ModelsLoginRequest} request User login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost(request: ModelsLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModelsAuthResponse> {
            return localVarFp.authLoginPost(request, options).then((request) => request(axios, basePath));
        },
        /**
         * Invalidate user session (client-side token removal)
         * @summary User logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.authLogoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Get current authenticated user\'s profile
         * @summary Get user profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authProfileGet(options?: RawAxiosRequestConfig): AxiosPromise<ModelsUserResponse> {
            return localVarFp.authProfileGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new user account with email, password, and role
         * @summary Register a new user
         * @param {ModelsRegisterRequest} request User registration data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost(request: ModelsRegisterRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModelsAuthResponse> {
            return localVarFp.authRegisterPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * Authenticate user with email and password
     * @summary User login
     * @param {ModelsLoginRequest} request User login credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLoginPost(request: ModelsLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLoginPost(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invalidate user session (client-side token removal)
     * @summary User logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLogoutPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLogoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get current authenticated user\'s profile
     * @summary Get user profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authProfileGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authProfileGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new user account with email, password, and role
     * @summary Register a new user
     * @param {ModelsRegisterRequest} request User registration data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authRegisterPost(request: ModelsRegisterRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRegisterPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProfilesApi - axios parameter creator
 * @export
 */
export const ProfilesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete the profile of the authenticated user
         * @summary Delete user profile
         * @param {string} authorization Bearer token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesDelete: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('profilesDelete', 'authorization', authorization)
            const localVarPath = `/profiles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the profile of the authenticated user
         * @summary Get user profile
         * @param {string} authorization Bearer token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('profilesGet', 'authorization', authorization)
            const localVarPath = `/profiles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new profile for the authenticated user
         * @summary Create user profile
         * @param {string} authorization Bearer token
         * @param {ModelsCreateProfileRequest} profile Profile data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesPost: async (authorization: string, profile: ModelsCreateProfileRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('profilesPost', 'authorization', authorization)
            // verify required parameter 'profile' is not null or undefined
            assertParamExists('profilesPost', 'profile', profile)
            const localVarPath = `/profiles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profile, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get public profiles with optional filtering by expertise, interests, location, and role
         * @summary Get public profiles
         * @param {Array<string>} [expertise] Filter by expertise (comma-separated)
         * @param {Array<string>} [interests] Filter by interests (comma-separated)
         * @param {string} [location] Filter by location
         * @param {string} [role] Filter by role (mentor, mentee, admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesPublicGet: async (expertise?: Array<string>, interests?: Array<string>, location?: string, role?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/profiles/public`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (expertise) {
                localVarQueryParameter['expertise'] = expertise.join(COLLECTION_FORMATS.csv);
            }

            if (interests) {
                localVarQueryParameter['interests'] = interests.join(COLLECTION_FORMATS.csv);
            }

            if (location !== undefined) {
                localVarQueryParameter['location'] = location;
            }

            if (role !== undefined) {
                localVarQueryParameter['role'] = role;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update the profile of the authenticated user
         * @summary Update user profile
         * @param {string} authorization Bearer token
         * @param {ModelsUpdateProfileRequest} profile Profile update data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesPut: async (authorization: string, profile: ModelsUpdateProfileRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('profilesPut', 'authorization', authorization)
            // verify required parameter 'profile' is not null or undefined
            assertParamExists('profilesPut', 'profile', profile)
            const localVarPath = `/profiles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profile, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProfilesApi - functional programming interface
 * @export
 */
export const ProfilesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProfilesApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete the profile of the authenticated user
         * @summary Delete user profile
         * @param {string} authorization Bearer token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profilesDelete(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profilesDelete(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfilesApi.profilesDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the profile of the authenticated user
         * @summary Get user profile
         * @param {string} authorization Bearer token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profilesGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsProfile>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profilesGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfilesApi.profilesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new profile for the authenticated user
         * @summary Create user profile
         * @param {string} authorization Bearer token
         * @param {ModelsCreateProfileRequest} profile Profile data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profilesPost(authorization: string, profile: ModelsCreateProfileRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsProfile>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profilesPost(authorization, profile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfilesApi.profilesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get public profiles with optional filtering by expertise, interests, location, and role
         * @summary Get public profiles
         * @param {Array<string>} [expertise] Filter by expertise (comma-separated)
         * @param {Array<string>} [interests] Filter by interests (comma-separated)
         * @param {string} [location] Filter by location
         * @param {string} [role] Filter by role (mentor, mentee, admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profilesPublicGet(expertise?: Array<string>, interests?: Array<string>, location?: string, role?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsProfile>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profilesPublicGet(expertise, interests, location, role, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfilesApi.profilesPublicGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update the profile of the authenticated user
         * @summary Update user profile
         * @param {string} authorization Bearer token
         * @param {ModelsUpdateProfileRequest} profile Profile update data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profilesPut(authorization: string, profile: ModelsUpdateProfileRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsProfile>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profilesPut(authorization, profile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProfilesApi.profilesPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProfilesApi - factory interface
 * @export
 */
export const ProfilesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProfilesApiFp(configuration)
    return {
        /**
         * Delete the profile of the authenticated user
         * @summary Delete user profile
         * @param {string} authorization Bearer token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesDelete(authorization: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.profilesDelete(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the profile of the authenticated user
         * @summary Get user profile
         * @param {string} authorization Bearer token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesGet(authorization: string, options?: RawAxiosRequestConfig): AxiosPromise<ModelsProfile> {
            return localVarFp.profilesGet(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new profile for the authenticated user
         * @summary Create user profile
         * @param {string} authorization Bearer token
         * @param {ModelsCreateProfileRequest} profile Profile data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesPost(authorization: string, profile: ModelsCreateProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModelsProfile> {
            return localVarFp.profilesPost(authorization, profile, options).then((request) => request(axios, basePath));
        },
        /**
         * Get public profiles with optional filtering by expertise, interests, location, and role
         * @summary Get public profiles
         * @param {Array<string>} [expertise] Filter by expertise (comma-separated)
         * @param {Array<string>} [interests] Filter by interests (comma-separated)
         * @param {string} [location] Filter by location
         * @param {string} [role] Filter by role (mentor, mentee, admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesPublicGet(expertise?: Array<string>, interests?: Array<string>, location?: string, role?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelsProfile>> {
            return localVarFp.profilesPublicGet(expertise, interests, location, role, options).then((request) => request(axios, basePath));
        },
        /**
         * Update the profile of the authenticated user
         * @summary Update user profile
         * @param {string} authorization Bearer token
         * @param {ModelsUpdateProfileRequest} profile Profile update data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profilesPut(authorization: string, profile: ModelsUpdateProfileRequest, options?: RawAxiosRequestConfig): AxiosPromise<ModelsProfile> {
            return localVarFp.profilesPut(authorization, profile, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProfilesApi - object-oriented interface
 * @export
 * @class ProfilesApi
 * @extends {BaseAPI}
 */
export class ProfilesApi extends BaseAPI {
    /**
     * Delete the profile of the authenticated user
     * @summary Delete user profile
     * @param {string} authorization Bearer token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfilesApi
     */
    public profilesDelete(authorization: string, options?: RawAxiosRequestConfig) {
        return ProfilesApiFp(this.configuration).profilesDelete(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the profile of the authenticated user
     * @summary Get user profile
     * @param {string} authorization Bearer token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfilesApi
     */
    public profilesGet(authorization: string, options?: RawAxiosRequestConfig) {
        return ProfilesApiFp(this.configuration).profilesGet(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new profile for the authenticated user
     * @summary Create user profile
     * @param {string} authorization Bearer token
     * @param {ModelsCreateProfileRequest} profile Profile data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfilesApi
     */
    public profilesPost(authorization: string, profile: ModelsCreateProfileRequest, options?: RawAxiosRequestConfig) {
        return ProfilesApiFp(this.configuration).profilesPost(authorization, profile, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get public profiles with optional filtering by expertise, interests, location, and role
     * @summary Get public profiles
     * @param {Array<string>} [expertise] Filter by expertise (comma-separated)
     * @param {Array<string>} [interests] Filter by interests (comma-separated)
     * @param {string} [location] Filter by location
     * @param {string} [role] Filter by role (mentor, mentee, admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfilesApi
     */
    public profilesPublicGet(expertise?: Array<string>, interests?: Array<string>, location?: string, role?: string, options?: RawAxiosRequestConfig) {
        return ProfilesApiFp(this.configuration).profilesPublicGet(expertise, interests, location, role, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update the profile of the authenticated user
     * @summary Update user profile
     * @param {string} authorization Bearer token
     * @param {ModelsUpdateProfileRequest} profile Profile update data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfilesApi
     */
    public profilesPut(authorization: string, profile: ModelsUpdateProfileRequest, options?: RawAxiosRequestConfig) {
        return ProfilesApiFp(this.configuration).profilesPut(authorization, profile, options).then((request) => request(this.axios, this.basePath));
    }
}



