/* tslint:disable */
/* eslint-disable */
/**
 * Mentori API
 * A mentor-mentee matching platform API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mentori.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

