// Demo data for mentors and mentees
// This data is used only in the production demo branch

export interface DemoProfile {
  id: string;
  user_id: string;
  first_name: string;
  last_name: string;
  bio: string;
  avatar_url: string;
  expertise: string[];
  interests: string[];
  location: string;
  is_active: boolean;
  role: 'mentor' | 'mentee';
}

export const DEMO_MENTORS: DemoProfile[] = [
  {
    id: 'demo-mentor-1',
    user_id: 'demo-user-mentor-1',
    first_name: 'Maria',
    last_name: 'Korhonen',
    bio: 'Software engineer with 10 years in Helsinki tech scene. Helped 20+ newcomers land their first Finnish tech job. Passionate about making tech accessible.',
    avatar_url: 'https://ui-avatars.com/api/?name=Maria+Korhonen&background=4F46E5&color=fff&size=200',
    expertise: ['Find a Job', 'Tech Industry', 'Finnish Language Learning', 'Housing & Relocation'],
    interests: ['Tech & Gaming', 'Coffee Culture', 'Hiking & Outdoor', 'Reading & Books'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-2',
    user_id: 'demo-user-mentor-2',
    first_name: 'Jukka',
    last_name: 'Virtanen',
    bio: 'University professor and integration specialist. 15 years helping international students navigate Finnish higher education and career paths.',
    avatar_url: 'https://ui-avatars.com/api/?name=Jukka+Virtanen&background=DC2626&color=fff&size=200',
    expertise: ["Bachelor's Degree", "Master's Degree", 'Doctoral Studies', 'Education System'],
    interests: ['Reading & Books', 'Arts & Museums', 'Coffee Culture', 'Traveling'],
    location: 'Tampere',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-3',
    user_id: 'demo-user-mentor-3',
    first_name: 'Sanna',
    last_name: 'Laine',
    bio: 'Entrepreneur and business coach. Built 3 successful startups in Finland. Love helping immigrants start their own businesses here.',
    avatar_url: 'https://ui-avatars.com/api/?name=Sanna+Laine&background=059669&color=fff&size=200',
    expertise: ['Starting a Business', 'Banking & Finance', 'Networking & Socializing', 'Work-Life Balance'],
    interests: ['Foodie & Restaurants', 'Traveling', 'Board Games', 'Cooking & Baking'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-4',
    user_id: 'demo-user-mentor-4',
    first_name: 'Mikko',
    last_name: 'Heikkinen',
    bio: 'Finnish language teacher for 8 years, specialized in YKI test prep. My students have 95% pass rate. Make Finnish fun and practical!',
    avatar_url: 'https://ui-avatars.com/api/?name=Mikko+Heikkinen&background=7C3AED&color=fff&size=200',
    expertise: ['Finnish Language Learning', 'YKI Test Preparation', 'Integration & Culture', 'Education System'],
    interests: ['Musical Instruments', 'Music & Concerts', 'Coffee Culture', 'Hiking & Outdoor'],
    location: 'Turku',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-5',
    user_id: 'demo-user-mentor-5',
    first_name: 'Anna',
    last_name: 'Nieminen',
    bio: 'Healthcare professional and integration volunteer. Help navigate the Finnish healthcare system and family services. Mother of 3.',
    avatar_url: 'https://ui-avatars.com/api/?name=Anna+Nieminen&background=DB2777&color=fff&size=200',
    expertise: ['Healthcare System', 'Finnish Marriage & Family', 'Integration & Culture', 'Work-Life Balance'],
    interests: ['Cooking & Baking', 'Hiking & Outdoor', 'Reading & Books', 'Crafts & DIY'],
    location: 'Oulu',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-6',
    user_id: 'demo-user-mentor-6',
    first_name: 'Teemu',
    last_name: 'Koskinen',
    bio: 'Real estate agent specializing in helping expats find homes. Know every neighborhood in the capital region. Housing made easy.',
    avatar_url: 'https://ui-avatars.com/api/?name=Teemu+Koskinen&background=EA580C&color=fff&size=200',
    expertise: ['Housing & Relocation', 'Banking & Finance', 'Integration & Culture', 'Networking & Socializing'],
    interests: ['Cycling', 'Coffee Culture', 'Tech & Gaming', 'Gym & Fitness'],
    location: 'Espoo',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-7',
    user_id: 'demo-user-mentor-7',
    first_name: 'Laura',
    last_name: 'Mäkinen',
    bio: 'HR manager at a multinational. Reviewed 1000+ CVs. Help you craft perfect Finnish-style applications and ace interviews.',
    avatar_url: 'https://ui-avatars.com/api/?name=Laura+Makinen&background=0891B2&color=fff&size=200',
    expertise: ['Find a Job', 'Work-Life Balance', 'Networking & Socializing', 'Integration & Culture'],
    interests: ['Gym & Fitness', 'Running', 'Foodie & Restaurants', 'Bars & Nightlife'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-8',
    user_id: 'demo-user-mentor-8',
    first_name: 'Petri',
    last_name: 'Salo',
    bio: 'Winter sports enthusiast and outdoor guide. Been living in Lapland for 20 years. Show you how to love Finnish winter, not just survive it!',
    avatar_url: 'https://ui-avatars.com/api/?name=Petri+Salo&background=1E40AF&color=fff&size=200',
    expertise: ['Integration & Culture', 'Networking & Socializing', 'Housing & Relocation'],
    interests: ['Winter Sports', 'Hiking & Outdoor', 'Photography', 'Traveling'],
    location: 'Rovaniemi',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-9',
    user_id: 'demo-user-mentor-9',
    first_name: 'Kaisa',
    last_name: 'Rantanen',
    bio: 'University counselor and career advisor. Specialize in helping international students transition from studies to Finnish work life.',
    avatar_url: 'https://ui-avatars.com/api/?name=Kaisa+Rantanen&background=BE185D&color=fff&size=200',
    expertise: ["Master's Degree", 'Doctoral Studies', 'Find a Job', 'Education System'],
    interests: ['Arts & Museums', 'Reading & Books', 'Coffee Culture', 'Board Games'],
    location: 'Jyväskylä',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-10',
    user_id: 'demo-user-mentor-10',
    first_name: 'Ville',
    last_name: 'Nurmi',
    bio: 'Tech startup founder and angel investor. Can help with networking in Finnish tech ecosystem and career acceleration strategies.',
    avatar_url: 'https://ui-avatars.com/api/?name=Ville+Nurmi&background=7C2D12&color=fff&size=200',
    expertise: ['Starting a Business', 'Find a Job', 'Networking & Socializing', 'Banking & Finance'],
    interests: ['Tech & Gaming', 'Board Games', 'Coffee Culture', 'Cycling'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-11',
    user_id: 'demo-user-mentor-11',
    first_name: 'Henna',
    last_name: 'Lehtonen',
    bio: 'Multicultural family specialist and social worker. Married to a non-Finnish spouse. Navigate intercultural relationships and family life.',
    avatar_url: 'https://ui-avatars.com/api/?name=Henna+Lehtonen&background=0D9488&color=fff&size=200',
    expertise: ['Finnish Marriage & Family', 'Integration & Culture', 'Healthcare System', 'Housing & Relocation'],
    interests: ['Cooking & Baking', 'Traveling', 'Foodie & Restaurants', 'Arts & Museums'],
    location: 'Vantaa',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-12',
    user_id: 'demo-user-mentor-12',
    first_name: 'Antti',
    last_name: 'Järvinen',
    bio: 'Banking and finance professional. Help newcomers understand Finnish banking, taxation, and financial planning for long-term success.',
    avatar_url: 'https://ui-avatars.com/api/?name=Antti+Jarvinen&background=4338CA&color=fff&size=200',
    expertise: ['Banking & Finance', 'Housing & Relocation', 'Starting a Business', 'Integration & Culture'],
    interests: ['Gym & Fitness', 'Tech & Gaming', 'Movies & TV Shows', 'Bars & Nightlife'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-13',
    user_id: 'demo-user-mentor-13',
    first_name: 'Riikka',
    last_name: 'Hakala',
    bio: 'Fitness coach and wellness expert. Promote healthy Finnish lifestyle and help you stay active through dark winters. Mental health matters!',
    avatar_url: 'https://ui-avatars.com/api/?name=Riikka+Hakala&background=D97706&color=fff&size=200',
    expertise: ['Work-Life Balance', 'Integration & Culture', 'Healthcare System', 'Networking & Socializing'],
    interests: ['Gym & Fitness', 'Running', 'Winter Sports', 'Hiking & Outdoor'],
    location: 'Tampere',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-14',
    user_id: 'demo-user-mentor-14',
    first_name: 'Matti',
    last_name: 'Lahti',
    bio: 'Vocational education instructor. Help people find practical career paths and navigate Finnish apprenticeship and vocational training.',
    avatar_url: 'https://ui-avatars.com/api/?name=Matti+Lahti&background=047857&color=fff&size=200',
    expertise: ['Education System', 'Find a Job', 'Integration & Culture', 'YKI Test Preparation'],
    interests: ['Crafts & DIY', 'Winter Sports', 'Coffee Culture', 'Board Games'],
    location: 'Lahti',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-15',
    user_id: 'demo-user-mentor-15',
    first_name: 'Elina',
    last_name: 'Saari',
    bio: 'Art and design professional in Helsinki. Connected with creative communities. Help artists and creatives build networks and find opportunities.',
    avatar_url: 'https://ui-avatars.com/api/?name=Elina+Saari&background=9333EA&color=fff&size=200',
    expertise: ['Networking & Socializing', 'Find a Job', 'Integration & Culture', 'Starting a Business'],
    interests: ['Arts & Museums', 'Photography', 'Music & Concerts', 'Coffee Culture'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-16',
    user_id: 'demo-user-mentor-16',
    first_name: 'Jari',
    last_name: 'Peltonen',
    bio: 'Construction industry veteran. Know the ins and outs of skilled trades in Finland. Help you get certified and find work in construction.',
    avatar_url: 'https://ui-avatars.com/api/?name=Jari+Peltonen&background=B91C1C&color=fff&size=200',
    expertise: ['Find a Job', 'Education System', 'Banking & Finance', 'Housing & Relocation'],
    interests: ['Crafts & DIY', 'Gym & Fitness', 'Hiking & Outdoor', 'Coffee Culture'],
    location: 'Kuopio',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-17',
    user_id: 'demo-user-mentor-17',
    first_name: 'Susanna',
    last_name: 'Ranta',
    bio: 'Librarian and language enthusiast. Run conversation clubs. Make learning Finnish enjoyable through books, films, and cultural events.',
    avatar_url: 'https://ui-avatars.com/api/?name=Susanna+Ranta&background=0369A1&color=fff&size=200',
    expertise: ['Finnish Language Learning', 'Integration & Culture', 'YKI Test Preparation', 'Networking & Socializing'],
    interests: ['Reading & Books', 'Movies & TV Shows', 'Arts & Museums', 'Coffee Culture'],
    location: 'Turku',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-18',
    user_id: 'demo-user-mentor-18',
    first_name: 'Timo',
    last_name: 'Karjalainen',
    bio: 'Restaurant owner and food industry pro. Started from dishwasher to entrepreneur. Know how immigrants can succeed in hospitality.',
    avatar_url: 'https://ui-avatars.com/api/?name=Timo+Karjalainen&background=C2410C&color=fff&size=200',
    expertise: ['Starting a Business', 'Find a Job', 'Banking & Finance', 'Work-Life Balance'],
    interests: ['Foodie & Restaurants', 'Cooking & Baking', 'Bars & Nightlife', 'Traveling'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-19',
    user_id: 'demo-user-mentor-19',
    first_name: 'Nina',
    last_name: 'Virtamo',
    bio: 'Parent and education advocate. Navigated Finnish daycare and school system with 2 kids. Help families understand Finnish childcare.',
    avatar_url: 'https://ui-avatars.com/api/?name=Nina+Virtamo&background=BE123C&color=fff&size=200',
    expertise: ['Finnish Marriage & Family', 'Education System', 'Healthcare System', 'Integration & Culture'],
    interests: ['Cooking & Baking', 'Board Games', 'Hiking & Outdoor', 'Crafts & DIY'],
    location: 'Espoo',
    is_active: true,
    role: 'mentor',
  },
  {
    id: 'demo-mentor-20',
    user_id: 'demo-user-mentor-20',
    first_name: 'Ossi',
    last_name: 'Mäkelä',
    bio: 'IT consultant and remote work specialist. Help tech professionals land remote Finnish jobs from anywhere. Digital nomad lifestyle expert.',
    avatar_url: 'https://ui-avatars.com/api/?name=Ossi+Makela&background=6366F1&color=fff&size=200',
    expertise: ['Find a Job', 'Tech Industry', 'Work-Life Balance', 'Banking & Finance'],
    interests: ['Tech & Gaming', 'Traveling', 'Coffee Culture', 'Photography'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentor',
  },
];

export const DEMO_MENTEES: DemoProfile[] = [
  {
    id: 'demo-mentee-1',
    user_id: 'demo-user-mentee-1',
    first_name: 'Ahmed',
    last_name: 'Hassan',
    bio: 'Software developer from Egypt. Just moved to Helsinki 3 months ago. Looking for guidance on job hunting and networking in Finnish tech.',
    avatar_url: 'https://ui-avatars.com/api/?name=Ahmed+Hassan&background=10B981&color=fff&size=200',
    expertise: ['Find a Job', 'Finnish Language Learning', 'Integration & Culture'],
    interests: ['Tech & Gaming', 'Coffee Culture', 'Foodie & Restaurants', 'Cycling'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-2',
    user_id: 'demo-user-mentee-2',
    first_name: 'Priya',
    last_name: 'Sharma',
    bio: "Starting Master's in Computer Science at Aalto University. Need help understanding Finnish study system and part-time job opportunities.",
    avatar_url: 'https://ui-avatars.com/api/?name=Priya+Sharma&background=8B5CF6&color=fff&size=200',
    expertise: ["Master's Degree", 'Education System', 'Find a Job', 'Housing & Relocation'],
    interests: ['Reading & Books', 'Gym & Fitness', 'Coffee Culture', 'Arts & Museums'],
    location: 'Espoo',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-3',
    user_id: 'demo-user-mentee-3',
    first_name: 'Carlos',
    last_name: 'Rodriguez',
    bio: 'Architect from Spain. Want to get my qualifications recognized and find work in Finland. Also need help with YKI test preparation.',
    avatar_url: 'https://ui-avatars.com/api/?name=Carlos+Rodriguez&background=EF4444&color=fff&size=200',
    expertise: ['Find a Job', 'YKI Test Preparation', 'Finnish Language Learning', 'Education System'],
    interests: ['Arts & Museums', 'Photography', 'Hiking & Outdoor', 'Coffee Culture'],
    location: 'Tampere',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-4',
    user_id: 'demo-user-mentee-4',
    first_name: 'Yuki',
    last_name: 'Tanaka',
    bio: 'Japanese student finishing PhD in materials science. Planning to stay in Finland. Need guidance on career paths after graduation.',
    avatar_url: 'https://ui-avatars.com/api/?name=Yuki+Tanaka&background=F59E0B&color=fff&size=200',
    expertise: ['Doctoral Studies', 'Find a Job', 'Integration & Culture', 'Work-Life Balance'],
    interests: ['Tech & Gaming', 'Reading & Books', 'Winter Sports', 'Board Games'],
    location: 'Oulu',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-5',
    user_id: 'demo-user-mentee-5',
    first_name: 'Emma',
    last_name: 'Johnson',
    bio: 'British nurse relocating to Finland with my family. Need help navigating healthcare system, housing, and enrolling kids in school.',
    avatar_url: 'https://ui-avatars.com/api/?name=Emma+Johnson&background=EC4899&color=fff&size=200',
    expertise: ['Healthcare System', 'Finnish Marriage & Family', 'Housing & Relocation', 'Education System'],
    interests: ['Hiking & Outdoor', 'Cooking & Baking', 'Reading & Books', 'Gym & Fitness'],
    location: 'Turku',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-6',
    user_id: 'demo-user-mentee-6',
    first_name: 'Dmitri',
    last_name: 'Petrov',
    bio: 'IT specialist from Russia. Living in Finland for 1 year. Want to improve my Finnish and understand local work culture better.',
    avatar_url: 'https://ui-avatars.com/api/?name=Dmitri+Petrov&background=3B82F6&color=fff&size=200',
    expertise: ['Finnish Language Learning', 'Work-Life Balance', 'Integration & Culture', 'Networking & Socializing'],
    interests: ['Tech & Gaming', 'Winter Sports', 'Chess', 'Coffee Culture'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-7',
    user_id: 'demo-user-mentee-7',
    first_name: 'Fatima',
    last_name: 'Al-Rashid',
    bio: 'Entrepreneur from UAE. Want to start a business in Finland. Need guidance on regulations, banking, and business networking.',
    avatar_url: 'https://ui-avatars.com/api/?name=Fatima+Al-Rashid&background=14B8A6&color=fff&size=200',
    expertise: ['Starting a Business', 'Banking & Finance', 'Networking & Socializing', 'Integration & Culture'],
    interests: ['Foodie & Restaurants', 'Traveling', 'Bars & Nightlife', 'Shopping'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-8',
    user_id: 'demo-user-mentee-8',
    first_name: 'Lucas',
    last_name: 'Silva',
    bio: 'Brazilian chef looking to work in Finnish restaurant industry. Need help with finding job opportunities and adapting recipes to local taste.',
    avatar_url: 'https://ui-avatars.com/api/?name=Lucas+Silva&background=F97316&color=fff&size=200',
    expertise: ['Find a Job', 'Integration & Culture', 'Finnish Language Learning'],
    interests: ['Cooking & Baking', 'Foodie & Restaurants', 'Music & Concerts', 'Gym & Fitness'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-9',
    user_id: 'demo-user-mentee-9',
    first_name: 'Anna',
    last_name: 'Kowalska',
    bio: "Polish marketing professional. New to Tampere. Looking for networking opportunities and tips on breaking into Finland's marketing scene.",
    avatar_url: 'https://ui-avatars.com/api/?name=Anna+Kowalska&background=A855F7&color=fff&size=200',
    expertise: ['Find a Job', 'Networking & Socializing', 'Finnish Language Learning', 'Work-Life Balance'],
    interests: ['Arts & Museums', 'Bars & Nightlife', 'Coffee Culture', 'Traveling'],
    location: 'Tampere',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-10',
    user_id: 'demo-user-mentee-10',
    first_name: 'James',
    last_name: 'O\'Brien',
    bio: 'Irish teacher planning to move to Finland. Need info about getting teaching qualifications recognized and finding international school jobs.',
    avatar_url: 'https://ui-avatars.com/api/?name=James+OBrien&background=059669&color=fff&size=200',
    expertise: ['Find a Job', 'Education System', 'Housing & Relocation', 'Integration & Culture'],
    interests: ['Reading & Books', 'Board Games', 'Hiking & Outdoor', 'Coffee Culture'],
    location: 'Vantaa',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-11',
    user_id: 'demo-user-mentee-11',
    first_name: 'Maria',
    last_name: 'Gonzalez',
    bio: "Bachelor's student in Business at Jyväskylä University. Looking for internship opportunities and career guidance for international students.",
    avatar_url: 'https://ui-avatars.com/api/?name=Maria+Gonzalez&background=DC2626&color=fff&size=200',
    expertise: ["Bachelor's Degree", 'Find a Job', 'Education System', 'Networking & Socializing'],
    interests: ['Traveling', 'Foodie & Restaurants', 'Music & Concerts', 'Gym & Fitness'],
    location: 'Jyväskylä',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-12',
    user_id: 'demo-user-mentee-12',
    first_name: 'Chen',
    last_name: 'Wei',
    bio: 'Chinese data scientist. Recently got job offer in Helsinki. Need help with relocation, banking setup, and finding apartment.',
    avatar_url: 'https://ui-avatars.com/api/?name=Chen+Wei&background=7C3AED&color=fff&size=200',
    expertise: ['Housing & Relocation', 'Banking & Finance', 'Integration & Culture', 'Finnish Language Learning'],
    interests: ['Tech & Gaming', 'Board Games', 'Coffee Culture', 'Photography'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-13',
    user_id: 'demo-user-mentee-13',
    first_name: 'Sofia',
    last_name: 'Andersson',
    bio: 'Swedish journalist moving to Rovaniemi for new job. Want to learn about life in Lapland and how to embrace the extreme seasons.',
    avatar_url: 'https://ui-avatars.com/api/?name=Sofia+Andersson&background=0891B2&color=fff&size=200',
    expertise: ['Integration & Culture', 'Housing & Relocation', 'Finnish Language Learning', 'Work-Life Balance'],
    interests: ['Winter Sports', 'Hiking & Outdoor', 'Photography', 'Coffee Culture'],
    location: 'Rovaniemi',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-14',
    user_id: 'demo-user-mentee-14',
    first_name: 'Michael',
    last_name: 'Brown',
    bio: 'American expat married to Finnish spouse. Recently moved here. Need guidance on integration, making friends, and career transition.',
    avatar_url: 'https://ui-avatars.com/api/?name=Michael+Brown&background=EA580C&color=fff&size=200',
    expertise: ['Finnish Marriage & Family', 'Integration & Culture', 'Find a Job', 'Networking & Socializing'],
    interests: ['Gym & Fitness', 'Winter Sports', 'Tech & Gaming', 'Bars & Nightlife'],
    location: 'Lahti',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-15',
    user_id: 'demo-user-mentee-15',
    first_name: 'Noor',
    last_name: 'Ahmed',
    bio: 'Graphic designer from Pakistan. Freelancing remotely. Want to build local client base and understand Finnish business culture.',
    avatar_url: 'https://ui-avatars.com/api/?name=Noor+Ahmed&background=DB2777&color=fff&size=200',
    expertise: ['Starting a Business', 'Networking & Socializing', 'Banking & Finance', 'Integration & Culture'],
    interests: ['Arts & Museums', 'Photography', 'Coffee Culture', 'Crafts & DIY'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-16',
    user_id: 'demo-user-mentee-16',
    first_name: 'Henrik',
    last_name: 'Jensen',
    bio: 'Danish electrician looking to work in Finland. Need help understanding certification requirements and finding job opportunities.',
    avatar_url: 'https://ui-avatars.com/api/?name=Henrik+Jensen&background=0D9488&color=fff&size=200',
    expertise: ['Find a Job', 'Education System', 'Housing & Relocation', 'Finnish Language Learning'],
    interests: ['Crafts & DIY', 'Gym & Fitness', 'Winter Sports', 'Coffee Culture'],
    location: 'Kuopio',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-17',
    user_id: 'demo-user-mentee-17',
    first_name: 'Aisha',
    last_name: 'Mohammed',
    bio: 'Nigerian social worker starting Master\'s program. Want to understand Finnish social services and build professional network here.',
    avatar_url: 'https://ui-avatars.com/api/?name=Aisha+Mohammed&background=BE185D&color=fff&size=200',
    expertise: ["Master's Degree", 'Education System', 'Healthcare System', 'Integration & Culture'],
    interests: ['Reading & Books', 'Arts & Museums', 'Coffee Culture', 'Cooking & Baking'],
    location: 'Turku',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-18',
    user_id: 'demo-user-mentee-18',
    first_name: 'Thomas',
    last_name: 'Schmidt',
    bio: 'German mechanical engineer. Got job in Oulu. Need advice on adapting to northern Finland and finding social activities.',
    avatar_url: 'https://ui-avatars.com/api/?name=Thomas+Schmidt&background=4338CA&color=fff&size=200',
    expertise: ['Integration & Culture', 'Work-Life Balance', 'Housing & Relocation', 'Networking & Socializing'],
    interests: ['Cycling', 'Winter Sports', 'Tech & Gaming', 'Board Games'],
    location: 'Oulu',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-19',
    user_id: 'demo-user-mentee-19',
    first_name: 'Linh',
    last_name: 'Nguyen',
    bio: 'Vietnamese restaurant owner. Want to open Asian restaurant in Helsinki. Need business mentorship and understanding of local food regulations.',
    avatar_url: 'https://ui-avatars.com/api/?name=Linh+Nguyen&background=D97706&color=fff&size=200',
    expertise: ['Starting a Business', 'Banking & Finance', 'Integration & Culture', 'Finnish Language Learning'],
    interests: ['Cooking & Baking', 'Foodie & Restaurants', 'Traveling', 'Coffee Culture'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentee',
  },
  {
    id: 'demo-mentee-20',
    user_id: 'demo-user-mentee-20',
    first_name: 'Isabella',
    last_name: 'Rossi',
    bio: 'Italian artist and designer. Moving to Finland for love. Need help finding art community, exhibition opportunities, and part-time work.',
    avatar_url: 'https://ui-avatars.com/api/?name=Isabella+Rossi&background=9333EA&color=fff&size=200',
    expertise: ['Find a Job', 'Finnish Marriage & Family', 'Networking & Socializing', 'Integration & Culture'],
    interests: ['Arts & Museums', 'Photography', 'Music & Concerts', 'Crafts & DIY'],
    location: 'Helsinki',
    is_active: true,
    role: 'mentee',
  },
];

export function getDemoProfiles(role?: 'mentor' | 'mentee'): DemoProfile[] {
  if (role === 'mentor') return DEMO_MENTORS;
  if (role === 'mentee') return DEMO_MENTEES;
  return [...DEMO_MENTORS, ...DEMO_MENTEES];
}

export function searchDemoProfiles(filters: {
  role?: 'mentor' | 'mentee';
  location?: string;
  expertise?: string[];
  interests?: string[];
}): DemoProfile[] {
  let profiles = getDemoProfiles(filters.role);

  if (filters.location) {
    profiles = profiles.filter(p => p.location === filters.location);
  }

  if (filters.expertise && filters.expertise.length > 0) {
    profiles = profiles.filter(p =>
      filters.expertise!.some(exp => p.expertise.includes(exp))
    );
  }

  if (filters.interests && filters.interests.length > 0) {
    profiles = profiles.filter(p =>
      filters.interests!.some(int => p.interests.includes(int))
    );
  }

  return profiles;
}
